[package]
name = "plugin"
version = "0.1.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plugin_manager_lib = {git = "https://github.com/MC-PMA/plugin_manager_lib" }
