[package]
name = "pmaapi"
version = "0.1.0"
edition = "2021"

[lib]
name = "pmaapi"
crate-type = ["dylib"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

libloader="0.1.4"